name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    name: Build and Test # More descriptive name for the build job
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: ntools-launcher.sln
      Test_Project_Path: LauncherTests\LauncherTests.csproj
      DevDrive: 'D:'
      MainDir: 'a\ntools-launcher'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Install ntools
    - name: Install ntools
      run: |
        cd ./DevSetup
        ./install-ntools.ps1 -devDrive "${{ env.DevDrive }}" -mainDir "${{ env.MainDir }}"
      shell: pwsh
      working-directory: ${{ github.workspace }}

    # Set ProgramFilesPath
    - name: Set ProgramFilesPath
      run: |
        $programFilesPath = [System.Environment]::GetFolderPath('ProgramFiles')
        echo "ProgramFilesPath=$programFilesPath" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh
   
    # Configure Git
    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

    # Build Staging using ntools
    - name: Run nb.exe
      run: |
        & "$env:ProgramFilesPath/nbuild/nb.exe" staging
      shell: pwsh
      working-directory: ${{ github.workspace }}
      env:
        VTAPIKEY: ${{ secrets.VTAPIKEY }}
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

  docs:
    name: Publish docs  # More descriptive name for the docs job
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies	
        run: |	
          python -m pip install --upgrade pip	
          pip install mkdocs	
      - name: Update docs	
        run: |	
          mkdocs build	
          mkdocs gh-deploy --force
