name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: ntools-launcher.sln
      Test_Project_Path: LauncherTests\LauncherTests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Install dependencies
      run: dotnet restore

    # Execute all unit tests in the solution
    - name: Build the solution
      run: dotnet build --no-restore --verbosity normal

    - name: Execute unit tests
      #run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      env:
        VTAPIKEY: ${{ secrets.VTAPIKEY }}
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      run: dotnet test --no-build --verbosity normal

        

